### ISSUE TITLE
Gaps in covering supplied regions

### ISSUE THREAD

**Issue by kaitlinleanne** [shendurelab/MIPGEN#13]
Hello, 

I'm attempting to generate some probes for a gene. I've used the program for a few genes thus far and all has worked fine!

Now, however, I'm getting a warning message at the end of the bash output:
 [mipgen] WARNING: There are 66 gaps in covering supplied regions

I've checked the bed file as well as running the same settings for other genes. The all_mips.txt file has plenty of mips in it. It would appear that the only issue is picking mips for the picked_mips.txt file. 

Any advice you could provide would be much appreciated!

**Comment by augustboyle** [comment]
Hello,

There are a few things that could cause this. Can you look at the failure flag column in the all MIPs file? The simplest explanation is that the regions do not map uniquely to the genome, which should trigger a flag and prevent those from being selected. There is an option to enable non-unique MIPs, but we have not come up with an analysis solution for non-unique MIPs with respect to mapping, so that's something to consider.

If there are lots of low scoring MIPs, that can also cause the program to choke depending on the options (i.e. double tiling etc). This can be changed by setting the priority_score and optimal_score options.

Checking the sequence is also important: if the all MIPs files have sequences with Ns in them, the program will freak out a little bit and probably leave gaps.

I think those are the main reasons I can think of.

Best,
Evan

**Comment by kaitlinleanne** [comment]
Hi, Evan. Thanks for the speedy reply.

You're right; the MIPs all have error flags attached to them. They all have 10 followed by either an A, T, C, G or /, with several having no third character. As I understand you and the README.md file, this represents a non-uniqueness with respect to the genome I am aligning to. Is that correct?
So I can fix this with providing the option:
-check_copy_number off
?

Thanks for your help,

Kaitlin

**Comment by kaitlinleanne** [comment]
Providing 
-check_copy_number off 
fixed it! Thanks for the help. 

Kaitlin
