### ISSUE TITLE
PCR amplification of MIPs oligos

### ISSUE THREAD

**Issue by rdoan** [shendurelab/MIPGEN#14]
Hello,
Do you have a specific recommended protocol for amplifying ssDNA MIPs designed through MIPGen? For example specific polymerase, ng of input, number of cycles? Your supplemental states "8. PCR amplification was performed with unphosphorylated forward primer and phosphorylated reverse primer."

Also you use a 200:1 ratio, does this mean that for 18,000 MIPs and 250ng starting DNA, I shoudl use about 15ng of MIPs per sample?

Thanks for the help,
Ryan

**Comment by augustboyle** [comment]
Hi Ryan,

That sounds about right. It will depend on the length of your MIPs. If they are 80-mers you might want a little more.

The ratio of genomic DNA to MIP DNA should be approximately 3.1*10**9 genomic bp / (80 bps per MIP * 18000 MIPs) / 200 as per the ratio => 10.8. For 250ng genomic DNA, you then want 250 / 10.8 = 23 ng of MIPs. At least, I believe the number quoted is for haploid genomes -- it's been a while!

Ratios up to 800:1 are generally well tolerated before rebalancing, although if you have 18,000 MIPs, chances are you won't be doing individual synthesis and rebalancing! Since you have many MIP targets, I would recommend exploring higher MIP ratios, in particular.

We do not have a specific recommendation for amplification. You may add multiple adaptors in an array and amplify MIPs in pools to improve uniformity or amplify entirely different MIP capture sets. The protocol I used in the paper is actually not ideal for large or even medium sized cohorts as it is difficult to obtain a high yield. Other strategies are likely superior, especially if you have more than a handful of samples. Here's one idea that generated some interest: http://www.ncbi.nlm.nih.gov/pubmed/25414325 . I think the consensus is that degrading both strands is not necessary or recommended, whatever the protocol, as the MIPs do not seem to interfere with alternate strand capture (as you might expect a priori), so following amplification and restriction, I would not do a lambda digestion.

Good luck with your experiments! I may take some time to reply, but feel free to ask me additional questions.

Evan Boyle
Graduate Student
Greenleaf & Pritchard Labs
Stanford University

On Nov 13, 2015, at 10:31 AM, rdoan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
Do you have a specific recommended protocol for amplifying ssDNA MIPs designed through MIPGen? For example specific polymerase, ng of input, number of cycles? Your supplemental states "8. PCR amplification was performed with unphosphorylated forward primer and phosphorylated reverse primer."

Also you use a 200:1 ratio, does this mean that for 18,000 MIPs and 250ng starting DNA, I shoudl use about 15ng of MIPs per sample?

Thanks for the help,
Ryan

**Comment by rdoan** [comment]
Hi Evan,

Thank you for all of the great information. If using the double stranded MIPs like you mentioned, the ligation/extrension arms need to be filtered to removed RE binding sites. Is there a way to tell MipGen to exclude specific sequence motifs? Also, I would not be able to use the NlaIII or StyD4I sites since they leave overhangs on the MIPs that might interfere with their hybridization to the genomic targets.

Thanks
Ryan

**Comment by augustboyle** [comment]
Hi Ryan,

There really SHOULD be a way to filter -- that functionality was lost over the course of development. It wouldn't be too much work, so I should probably add that in. I'm occupied with other things currently, so in the meantime you could try to implement it yourself (fork it on GitHub to share it!), filter things post hoc (not very fun), or run MIPgen, get the sequence targets, find the coordinates of any motifs in the targets, add the coordinates to the SNP file (MIPgen should also print out a new file of just the local SNPs so you can rerun with just those, with a new file name and reindexed of course), and then remove MIPs with SNP failure.

You would want to use type IIS restriction enzymes a la the paper I sent you. MlyI might be preferable because it is blunt-ended, but some overhang (which would change the targeting arms slightly) would be acceptable as well, and there should be many of those. Hope that helps!

Best,
Evan
