### ISSUE TITLE
MIP probe design strand issue,  SNP in the probe and probe synthesis

### ISSUE THREAD

**Issue by LINLIUNIG** [shendurelab/MIPGEN#15]
Hello,
Finally I let the MIPgen software run properly and get my probes designed.
But I am still not quite sure about several things. Therefore would like to ask for advice or suggestions.
1. Every two successive MIP probes are not already on the opposite strands.  I realized that the publication from Brian J. O'Roak et al.Science 338, 1619 (2012) designed the probes in this way that they have to be always on the opposite strands. Does this really matter? How to use the settings in MIPgen to generate two successive MIP probes on opposite strands.
2. I got quite names in the mip_name column like (XXX_SNP_a) in the final mip_picked output file.
What does it mean? It means that a probe is designed successfully against one allele of a SNP, but not the other? If this is the case, how can I design a probe against the second allele?
3. As I plan to synthesis the probes individually before pooling, does the probe synthesis need some modification or it is just like the normal primer synthesis?

Many thanks for your attention and reply.

Li

**Comment by augustboyle** [comment]
Hello Li,

I’m glad you got things working. Here are my responses to your questions:

1. We have found that it does not seem to make a difference whether probes are designed in this way. For troublesome high GC/high copy regions, it might be preferable to alternate strands, but these regions are challenging regardless, and so we didn’t determine this conclusively. You can, however, design to each strand separately and then manually pick mostly alternating strands (definitely could be a lot of work depending on your target size).
2. The “a” alleles are the reference allele MIPs. The non-reference allele MIPs are in the SNP MIP files, not the picked MIP file. This was done to make analysis less confusing (so that there wouldn’t be multiple MIPs with the same coordinates).
3. Standard oligo synthesis should apply for MIPs — no need for modification or special purification.

Best,
Evan

**Comment by LINLIUNIG** [comment]
Dear Evan,
Many thanks for your quick reply. 
Your message you gave me is really important.
Regarding the GC rich regions, do you have other suggestions about the probe design? If yes, I would like to pay attention to them in the very beginning. 
Regarding the question 2, I pretty much understood. when we have such cases (XX-SNP), that indicates the probe contain one SNP, right? I guess I still need to synthesis two probes against two different alleles?

Many thanks for your support!

Best,
Li

**Comment by augustboyle** [comment]
Hi Li,

I don’t have much else to advise with respect to high GC regions. Only that low scoring probes may not capture their targets efficiently. If your probe set is unusually low-scoring (i.e. >20% with scores lower than the default values), you might consider increasing the specificity of the set by lower the max_copy_arm_product option. The probe arms will then be more unique and less likely to hybridize non-specifically due to the GC interactions.

And that is correct, for SNP MIPs, you need to order multiple oligos per target.

Good luck!

Evan

**Comment by LINLIUNIG** [comment]
Hi Evan,
Many thanks for your reply!
I noted your advice . 
I have ordered several probes and will make some test.
Best wishes,
Li
