### ISSUE TITLE
BWA file

### ISSUE THREAD

**Issue by YuliaGo** [shendurelab/MIPGEN#18]
Hi!
We are very new in using MIPGEN, but very exited to start working with it!  What are we supposed to write after the "-bwa_genome_index"? When we try to run MIPGEN we get the following error:
bwa: command not found
load bwa
unable to tile sequences due to circumstance 2

Does MIPGEN is supposed to receive fasta file and run bwa on it by itself or should we provide the path of the BWA output files? If BWA (and the other dependencies you mentioned, sam tools and tabix) is supposed to be run by the MIPGEN code, where should these be saved so it can be accessible? 

Thank you in advance!

**Comment by augustboyle** [comment]
Hi Lauren,

Have you exported your PATH variable? Basically when you run the MIPgen
command it will start up a new shell. By default it will run the .bashrc
profile. This could reset your PATH variable if you have changed it in your
interactive session.

Solutions to this are providing the bwa path to the -bwa option, editing
the PATH variable in your .bashrc profile or running export PATH=$PATH:<bwa
path> which will preserve the PATH variable for shells that are called in
the future.

Hope that helps!
Evan


On October 29, 2018 at 11:24:20 PM, lauren-a (notifications@github.com)
wrote:

I have the same problem when I try to run MIPgen (the tutorial):

$ ../mipgen -regions_to_scan practice_genes.bed -project_name practice_run
-min_capture_size 162 -max_capture_size 162 -bwa_genome_index
human_g1k_v37.fasta
sh: 1: bwa: not found
load bwa
unable to tile sequences due to circumstance 2

From looking at other MIPgen issues on GitHub, I'm supposed to see the BWA
program version info first, before MIPgen tries to actually run my
analysis. So it looks like it can't find BWA - but when I type "bwa" into
my terminal then it does find BWA (I attached it to my path manually),
leaving me very confused.

Any suggestions/help greatly appreciated!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/18#issuecomment-434185929>,
or mute the thread

**Comment by lauren-a** [comment]
Hi Evan,

I added "export PATH=$PATH:<bwa path>" to my .bashrc file, so it should work for all new sessions. But I had some issues installing bwa in the first place, so perhaps there's a different issue. Do I need to build the BWA index before running MIPgen, or should MIPgen do that for me?

Thanks,
Lauren

**Comment by augustboyle** [comment]
Hi,

You will need to index your genome before running MIPgen (it is not
automatic currently).

Definitely doing some test aligning beforehand should be helpful to make
sure bwa is working. One thing to try is to go to a different directory and
see if it still runs. The install might have been partially complete but
missing some files that are discoverable only from certain directories.
Another thing to confirm is logging into a new session and testing whether
the command works.

Evan

On October 29, 2018 at 11:33:52 PM, lauren-a (notifications@github.com)
wrote:

Hi Evan,

I added "export PATH=$PATH:" to my .bashrc file, so it should work for all
new sessions. But I had some issues installing bwa in the first place, so
perhaps there's a different issue. Do I need to build the BWA index before
running MIPgen, or should MIPgen do that for me?

Thanks,
Lauren

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/18#issuecomment-434187529>,
or mute the thread
