### ISSUE TITLE
Using_more_than_1_snpfile

### ISSUE THREAD

**Issue by ECarbo** [shendurelab/MIPGEN#20]
Hi Evan,

first of all: great tool! I am new to MIPGEN but I have a small question about using snp files. If I run the tool for instance with these default settings:
-snp_file vcf1.vcf
-snp_file vcf2.vcf
Does the tool then take both snp files into account? Or is this not possible?

Kind regards, Ellen

**Comment by augustboyle** [comment]
Hi Ellen,

Thanks! As to your question, while I have definitely encountered that scenario myself, MIPgen does not take multiple SNP files. All the options are parsed by C++ without much help from external libraries, so it would be a little complicated to permit multiple files.

I would have come up with something, but I have always settled for concatenating the VCFs. If you run MIPgen with a VCF, it will try to pull out all the SNPs overlapping your regions in the VCF. I generally find that the fastest way to get files that aren’t huge is to run MIPgen with one VCF, take the VCF output file specific to the targeted regions and concatenate it with the other VCF before running it a second time using the concatenated file. If you need to use multiple VCF’s SNPs many times it would be worth concatenating them to begin with, of course.

It’s pretty annoying but it shouldn’t take long (hence why I haven’t added this functionality). You can kill the MIPgen process the first time before it tiles the regions since you only need the VCF.

Hope that helps!

Evan Boyle
Genetics graduate student
Pritchard & Greenleaf labs
Stanford University

**Comment by ECarbo** [comment]
Hi Evan,

Merging the VCF files is of course no problem. I just wanted to know if it was possible for MIPGEN to handle two or more directly. Thanks for the quick reply!! 

Ellen

**Comment by augustboyle** [comment]
No support to date :)
