### ISSUE TITLE
Dense MIP coverage of region

### ISSUE THREAD

**Issue by rdoan** [shendurelab/MIPGEN#21]
Hello, I know that MIPgen has the ability to double tile a region, however, is it possible to densely tile a region so that I have say 4 or 5 MIPs for every site? It seems that MIPgen should be able to do this since it creates a list of all MIPs for a region in the collapsed_mips file.

Thanks
Ryan

**Comment by augustboyle** [comment]
Hi Ryan,

You can certainly pull MIPs from the related files to do such a tiling but
there is no combination of options to permit this in MIPgen. Typically the
arms overlap once you go past triple tiling anyway. The closest solution is
to double tile strands separately and double tile strand unaware. This will
produce a 4x tiling without arm overlaps when possible, two per strand. The
missed bases should be printed out. You can always just choose a bunch of
high scoring MIPs however.

Evan

On September 7, 2016 at 2:09:00 PM, rdoan (notifications@github.com) wrote:

Hello, I know that MIPgen has the ability to double tile a region, however,
is it possible to densely tile a region so that I have say 4 or 5 MIPs for
every site? It seems that MIPgen should be able to do this since it creates
a list of all MIPs for a region in the collapsed_mips file.

Thanks
Ryan

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/21>, or mute the thread
