### ISSUE TITLE
no masked feature file found

### ISSUE THREAD

**Issue by JulieHachey** [shendurelab/MIPGEN#26]
Hi,

I am having issues running the practice gene tutorial. 0 SNPS found.

Please see output below.

$ mipgen -regions_to_scan practice_genes.bed -project_name practice_design -min_capture_size 162 -max_capture_size 162 -bwa_genome_index ...MIPGEN/human_g1k_v37.fasta

Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.15-r1140
Contact: Heng Li <lh3@sanger.ac.uk>

Usage:   bwa <command> [options]

Command: index         index sequences in the FASTA format
         mem           BWA-MEM algorithm
         fastmap       identify super-maximal exact matches
         pemerge       merge overlapping paired ends (EXPERIMENTAL)
         aln           gapped/ungapped alignment
         samse         generate alignment (single ended)
         sampe         generate alignment (paired ended)
         bwasw         BWA-SW for long queries

         shm           manage indices in shared memory
         fa2pac        convert FASTA to PAC format
         pac2bwt       generate BWT from PAC
         pac2bwtgen    alternative algorithm for generating BWT
         bwtupdate     update .bwt to the new format
         bwt2sa        generate SA from BWT and Occ

Note: To use BWA, you need to first index the genome with `bwa index'.
      There are three alignment algorithms in BWA: `mem', `bwasw', and
      `aln/samse/sampe'. If you are not sure which to use, try `bwa mem'
      first. Please `man ./bwa.1' for the manual.

[mipgen] success on opening region file
[mipgen] features loaded; retrieving chromosomal sequence

Program: samtools (Tools for alignments in the SAM format)
Version: 1.5 (using htslib 1.4.1)

Usage:   samtools <command> [options]

Commands:
  -- Indexing
     dict           create a sequence dictionary file
     faidx          index/extract FASTA
     index          index alignment

  -- Editing
     calmd          recalculate MD/NM tags and '=' bases
     fixmate        fix mate information
     reheader       replace BAM header
     rmdup          remove PCR duplicates
     targetcut      cut fosmid regions (for fosmid pool only)
     addreplacerg   adds or replaces RG tags

  -- File operations
     collate        shuffle and group alignments by name
     cat            concatenate BAMs
     merge          merge sorted alignments
     mpileup        multi-way pileup
     sort           sort alignment file
     split          splits a file by read group
     quickcheck     quickly check if SAM/BAM/CRAM file appears intact
     fastq          converts a BAM to a FASTQ
     fasta          converts a BAM to a FASTA

  -- Statistics
     bedcov         read depth per BED region
     depth          compute the depth
     flagstat       simple stats
     idxstats       BAM index stats
     phase          phase heterozygotes
     stats          generate stats (former bamcheck)

  -- Viewing
     flags          explain BAM flags
     tview          text alignment viewer
     view           SAM<->BAM<->CRAM conversion
     depad          convert padded BAM to unpadded BAM

[mipgen] first line of reference fasta reads: >1 dna:chromosome chromosome:GRCh37:1:1:249250621:1
[mipgen] no masked feature file found
[mipgen] regions ready; accessing snp file
[mipgen] all 0 snps loaded; generating files for bwa
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln_core] calculate SA coordinate... 3.96 sec
[bwa_aln_core] write to the disk... 0.00 sec
[bwa_aln_core] 19893 sequences have been processed.
[main] Version: 0.7.15-r1140
[main] CMD: bwa aln -t 1 ...MIPGEN/human_g1k_v37.fasta practice_design.all_sequences.fq
[main] Real time: 7.973 sec; CPU: 7.125 sec
[bwa_aln_core] convert to sequence coordinate... 4.97 sec
[bwa_aln_core] refine gapped alignments... 0.61 sec
[bwa_aln_core] print alignments... 0.04 sec
[bwa_aln_core] 19893 sequences have been processed.
[main] Version: 0.7.15-r1140
[main] CMD: bwa samse ...MIPGEN/human_g1k_v37.fasta practice_design.all_sequences.sai practice_design.all_sequences.fq
[main] Real time: 7.061 sec; CPU: 5.687 sec
[mipgen] sam file opened
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln_core] calculate SA coordinate... 15.54 sec
[bwa_aln_core] write to the disk... 0.09 sec
[bwa_aln_core] 262144 sequences have been processed.
[bwa_aln_core] calculate SA coordinate... 8.63 sec
[bwa_aln_core] write to the disk... 0.05 sec
[bwa_aln_core] 416934 sequences have been processed.
[main] Version: 0.7.15-r1140
[main] CMD: bwa aln -t 1 ...MIPGEN/human_g1k_v37.fasta practice_design.oligo_copy_count.fq
[main] Real time: 30.044 sec; CPU: 27.628 sec
[bwa_aln_core] convert to sequence coordinate... 8.53 sec
[bwa_aln_core] refine gapped alignments... 0.78 sec
[bwa_aln_core] print alignments... 0.47 sec
[bwa_aln_core] 262144 sequences have been processed.
[bwa_aln_core] convert to sequence coordinate... 6.92 sec
[bwa_aln_core] refine gapped alignments... 0.63 sec
[bwa_aln_core] print alignments... 0.28 sec
[bwa_aln_core] 416934 sequences have been processed.
[main] Version: 0.7.15-r1140
[main] CMD: bwa samse ...MIPGEN/human_g1k_v37.fasta practice_design.oligo_copy_count.sai practice_design.oligo_copy_count.fq
[main] Real time: 21.494 sec; CPU: 18.068 sec
[mipgen] checking oligo copy
[mipgen] bwa copy number analysis finished
[mipgen] file of all mips ready for write: practice_design.all_mips.txt
[mipgen] file of collapsed mips ready for write: practice_design.collapsed_mips.txt
[mipgen] feature #1
[mipgen] feature #2
[mipgen] feature #3
[mipgen] feature #4
[mipgen] feature #5
[mipgen] feature #6
[mipgen] feature #7
[mipgen] feature #8
[mipgen] feature #9
[mipgen] feature #10
[mipgen] feature #11
[mipgen] feature #12
[mipgen] feature #13
[mipgen] feature #14
[mipgen] feature #15
[mipgen] feature #16
[mipgen] feature #17
[mipgen] feature #18
[mipgen] feature #19
[mipgen] feature #20
[mipgen] feature #21
[mipgen] feature #22
[mipgen] feature #23
[mipgen] feature #24
[mipgen] feature #25
[mipgen] feature #26
[mipgen] feature #27
[mipgen] feature #28
[mipgen] feature #29
[mipgen] feature #30
[mipgen] feature #31
[mipgen] feature #32
[mipgen] feature #33
[mipgen] feature #34
[mipgen] feature #35
[mipgen] feature #36
[mipgen] feature #37
[mipgen] feature #38
[mipgen] feature #39
[mipgen] feature #40
[mipgen] feature #41
[mipgen] feature #42
[mipgen] feature #43
[mipgen] feature #44
[mipgen] feature #45
[mipgen] feature #46
[mipgen] feature #47
[mipgen] feature #48
[mipgen] feature #49
[mipgen] feature #50
[mipgen] feature #51
[mipgen] feature #52
[mipgen] feature #53
[mipgen] feature #54
[mipgen] feature #55
[mipgen] feature #56
[mipgen] feature #57
[mipgen] feature #58
[mipgen] feature #59
[mipgen] feature #60
[mipgen] feature #61
[mipgen] feature #62
[mipgen] feature #63
[mipgen] feature #64
[mipgen] mip picking complete:
practice_design.picked_mips.txt
 and 
practice_design.snp_mips.txt

Thanks!

**Comment by augustboyle** [comment]
Hello,

It looks like you are missing the snp_file argument. If you want to design
around SNPs than you need a VCF of SNPs to load. Without supplying that
argument zero SNPs will be loaded!

It looks like you can download a list of common SNPs here:
ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/common_all_20170403.vcf.gz

Are there MIPs present in the output file? It seems like it could be
working aside from that.

Evan

On July 6, 2017 at 12:25:08 PM, jgithhub (notifications@github.com) wrote:

Hi,

I am having issues running the practice gene tutorial. 0 SNPS found.

Please see output below.

$ mipgen -regions_to_scan practice_genes.bed -project_name practice_design
-min_capture_size 162 -max_capture_size 162 -bwa_genome_index
...MIPGEN/human_g1k_v37.fasta

Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.15-r1140
Contact: Heng Li lh3@sanger.ac.uk

Usage: bwa [options]

Command: index index sequences in the FASTA format
mem BWA-MEM algorithm
fastmap identify super-maximal exact matches
pemerge merge overlapping paired ends (EXPERIMENTAL)
aln gapped/ungapped alignment
samse generate alignment (single ended)
sampe generate alignment (paired ended)
bwasw BWA-SW for long queries

     shm           manage indices in shared memory
     fa2pac        convert FASTA to PAC format
     pac2bwt       generate BWT from PAC
     pac2bwtgen    alternative algorithm for generating BWT
     bwtupdate     update .bwt to the new format
     bwt2sa        generate SA from BWT and Occ

Note: To use BWA, you need to first index the genome with bwa index'. There
are three alignment algorithms in BWA:mem', bwasw', andaln/samse/sampe'. If
you are not sure which to use, try bwa mem' first. Pleaseman ./bwa.1' for
the manual.

[mipgen] success on opening region file
[mipgen] features loaded; retrieving chromosomal sequence

Program: samtools (Tools for alignments in the SAM format)
Version: 1.5 (using htslib 1.4.1)

Usage: samtools [options]

Commands:
-- Indexing
dict create a sequence dictionary file
faidx index/extract FASTA
index index alignment

-- Editing
calmd recalculate MD/NM tags and '=' bases
fixmate fix mate information
reheader replace BAM header
rmdup remove PCR duplicates
targetcut cut fosmid regions (for fosmid pool only)
addreplacerg adds or replaces RG tags

-- File operations
collate shuffle and group alignments by name
cat concatenate BAMs
merge merge sorted alignments
mpileup multi-way pileup
sort sort alignment file
split splits a file by read group
quickcheck quickly check if SAM/BAM/CRAM file appears intact
fastq converts a BAM to a FASTQ
fasta converts a BAM to a FASTA

-- Statistics
bedcov read depth per BED region
depth compute the depth
flagstat simple stats
idxstats BAM index stats
phase phase heterozygotes
stats generate stats (former bamcheck)

-- Viewing
flags explain BAM flags
tview text alignment viewer
view SAM<->BAM<->CRAM conversion
depad convert padded BAM to unpadded BAM

[mipgen] first line of reference fasta reads: >1 dna:chromosome
chromosome:GRCh37:1:1:249250621:1
[mipgen] no masked feature file found
[mipgen] regions ready; accessing snp file
[mipgen] all 0 snps loaded; generating files for bwa
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln_core] calculate SA coordinate... 3.96 sec
[bwa_aln_core] write to the disk... 0.00 sec
[bwa_aln_core] 19893 sequences have been processed.
[main] Version: 0.7.15-r1140
[main] CMD: bwa aln -t 1 ...MIPGEN/human_g1k_v37.fasta
practice_design.all_sequences.fq
[main] Real time: 7.973 sec; CPU: 7.125 sec
[bwa_aln_core] convert to sequence coordinate... 4.97 sec
[bwa_aln_core] refine gapped alignments... 0.61 sec
[bwa_aln_core] print alignments... 0.04 sec
[bwa_aln_core] 19893 sequences have been processed.
[main] Version: 0.7.15-r1140
[main] CMD: bwa samse ...MIPGEN/human_g1k_v37.fasta
practice_design.all_sequences.sai practice_design.all_sequences.fq
[main] Real time: 7.061 sec; CPU: 5.687 sec
[mipgen] sam file opened
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln_core] calculate SA coordinate... 15.54 sec
[bwa_aln_core] write to the disk... 0.09 sec
[bwa_aln_core] 262144 sequences have been processed.
[bwa_aln_core] calculate SA coordinate... 8.63 sec
[bwa_aln_core] write to the disk... 0.05 sec
[bwa_aln_core] 416934 sequences have been processed.
[main] Version: 0.7.15-r1140
[main] CMD: bwa aln -t 1 ...MIPGEN/human_g1k_v37.fasta
practice_design.oligo_copy_count.fq
[main] Real time: 30.044 sec; CPU: 27.628 sec
[bwa_aln_core] convert to sequence coordinate... 8.53 sec
[bwa_aln_core] refine gapped alignments... 0.78 sec
[bwa_aln_core] print alignments... 0.47 sec
[bwa_aln_core] 262144 sequences have been processed.
[bwa_aln_core] convert to sequence coordinate... 6.92 sec
[bwa_aln_core] refine gapped alignments... 0.63 sec
[bwa_aln_core] print alignments... 0.28 sec
[bwa_aln_core] 416934 sequences have been processed.
[main] Version: 0.7.15-r1140
[main] CMD: bwa samse ...MIPGEN/human_g1k_v37.fasta
practice_design.oligo_copy_count.sai practice_design.oligo_copy_count.fq
[main] Real time: 21.494 sec; CPU: 18.068 sec
[mipgen] checking oligo copy
[mipgen] bwa copy number analysis finished
[mipgen] file of all mips ready for write: practice_design.all_mips.txt
[mipgen] file of collapsed mips ready for write:
practice_design.collapsed_mips.txt
[mipgen] feature #1 <https://github.com/shendurelab/MIPGEN/issues/1>
[mipgen] feature #2 <https://github.com/shendurelab/MIPGEN/issues/2>
[mipgen] feature #3 <https://github.com/shendurelab/MIPGEN/issues/3>
[mipgen] feature #4 <https://github.com/shendurelab/MIPGEN/issues/4>
[mipgen] feature #5 <https://github.com/shendurelab/MIPGEN/issues/5>
[mipgen] feature #6 <https://github.com/shendurelab/MIPGEN/issues/6>
[mipgen] feature #7 <https://github.com/shendurelab/MIPGEN/issues/7>
[mipgen] feature #8 <https://github.com/shendurelab/MIPGEN/issues/8>
[mipgen] feature #9 <https://github.com/shendurelab/MIPGEN/issues/9>
[mipgen] feature #10 <https://github.com/shendurelab/MIPGEN/issues/10>
[mipgen] feature #11 <https://github.com/shendurelab/MIPGEN/issues/11>
[mipgen] feature #12 <https://github.com/shendurelab/MIPGEN/issues/12>
[mipgen] feature #13 <https://github.com/shendurelab/MIPGEN/issues/13>
[mipgen] feature #14 <https://github.com/shendurelab/MIPGEN/issues/14>
[mipgen] feature #15 <https://github.com/shendurelab/MIPGEN/issues/15>
[mipgen] feature #16 <https://github.com/shendurelab/MIPGEN/issues/16>
[mipgen] feature #17 <https://github.com/shendurelab/MIPGEN/issues/17>
[mipgen] feature #18 <https://github.com/shendurelab/MIPGEN/issues/18>
[mipgen] feature #19 <https://github.com/shendurelab/MIPGEN/issues/19>
[mipgen] feature #20 <https://github.com/shendurelab/MIPGEN/issues/20>
[mipgen] feature #21 <https://github.com/shendurelab/MIPGEN/issues/21>
[mipgen] feature #22 <https://github.com/shendurelab/MIPGEN/issues/22>
[mipgen] feature #23 <https://github.com/shendurelab/MIPGEN/issues/23>
[mipgen] feature #24 <https://github.com/shendurelab/MIPGEN/issues/24>
[mipgen] feature #25 <https://github.com/shendurelab/MIPGEN/issues/25>
[mipgen] feature #26 <https://github.com/shendurelab/MIPGEN/issues/26>
[mipgen] feature #27
[mipgen] feature #28
[mipgen] feature #29
[mipgen] feature #30
[mipgen] feature #31
[mipgen] feature #32
[mipgen] feature #33
[mipgen] feature #34
[mipgen] feature #35
[mipgen] feature #36
[mipgen] feature #37
[mipgen] feature #38
[mipgen] feature #39
[mipgen] feature #40
[mipgen] feature #41
[mipgen] feature #42
[mipgen] feature #43
[mipgen] feature #44
[mipgen] feature #45
[mipgen] feature #46
[mipgen] feature #47
[mipgen] feature #48
[mipgen] feature #49
[mipgen] feature #50
[mipgen] feature #51
[mipgen] feature #52
[mipgen] feature #53
[mipgen] feature #54
[mipgen] feature #55
[mipgen] feature #56
[mipgen] feature #57
[mipgen] feature #58
[mipgen] feature #59
[mipgen] feature #60
[mipgen] feature #61
[mipgen] feature #62
[mipgen] feature #63
[mipgen] feature #64
[mipgen] mip picking complete:
practice_design.picked_mips.txt
and
practice_design.snp_mips.txt

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/26>, or mute the thread
