### ISSUE TITLE
using known isoform and oligos

### ISSUE THREAD

**Issue by JulieHachey** [shendurelab/MIPGEN#29]
Hi,

Would it be possible to generate mips against a known sequence without having to run it against the reference genome and skipping the BWA part? I would like to use RNA isoforms and short oligos.

Would it be possible to input our own Mip backbone?

Thanks!!

**Comment by augustboyle** [comment]
Hello,

BWA is used to determine the specificity of the probe so it does have to be
run, BUT you are welcome to use any reference you like to design the MIPs.
You can include all the oligos and isoforms you want to design to and build
your own BWA index. Then you would need to figure out the coordinates of
the region you want to have tiled.

The only caveats are that if you are capturing cDNA from an RNA-seq
library, I would recommend using the whole transcriptome of the organism,
and for scoring purposes, some flanking sequence is required beyond what
you want to tile exactly. Otherwise, you could design non-specific probes
that will yield lots of side products / the scoring will not work.

Good luck!

Evan


On October 3, 2017 at 5:10:55 AM, JgitHhub (notifications@github.com) wrote:

Hi,

Would it be possible to generate mips against a known sequence without
having to run it against the reference genome and skipping the BWA part? I
would like to use RNA isoforms and short oligos.

Would it be possible to input our own Mip backbone?

Thanks!!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/29>, or mute the thread

**Comment by JgitHhub** [comment]
Thank you for the information.

Would it be possible to import a fasta and have mips generated against the sequences provide instead of using the reference to find a sequence?

**Comment by augustboyle** [comment]
Hi,

It is straightforward to run bwa index on any fasta you like to generate a
new reference, so that shouldn’t be a problem! The variable is called
bwa_genome_index, but it doesn’t have to be a genome fasta. Just toss it in.

The only other thing is that gap filling MIPs perform poorly on DNA shorter
than about 1000 bp, so if you have very short libraries it might be quite
inefficient.

Evan


On October 3, 2017 at 10:52:46 AM, JgitHhub (notifications@github.com)
wrote:

Thank you for the information.

Would it be possible to import a fasta and have mips generated against the
sequences provide instead of using the reference to find a sequence?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/29#issuecomment-333925481>,
or mute the thread
