### ISSUE TITLE
Unable to reproduce results from older version.

### ISSUE THREAD

**Issue by LaurensHannes** [shendurelab/MIPGEN#30]
Hello,

I've been trying to reproduce results attained with version 0.9.1 using the newest version of the MIPGEN tool. However only 1/4th of the results are exactly the same. There remainder are different due to a difference in logstical scoring. The same thing happens with the practice files provided. I've tested using several different builds of hg19 and SNPdb builds. This only provides minor differences and doesn't seem to account for the overal difference.  

Am I forgetting/doing something wrong or is this expected due to the changes between the current version and older ones? 

Thanks,
Laurens

**Comment by augustboyle** [comment]
Hi Laurens,

Here’s the short answer: MIPgen v0.9.1 actually miscalculated MIP scores.
This was mitigated by the fact that the miscalculated scores were still
correlated with the true scores, and I think only 1/2 of the scores were
incorrect, although another 50% of the time a different MIP should be
chosen and could change the score distribution.

I was going to run the newest version for you and update the example, but
our lab's servers (where I have things already set up) had to be taken
offline and it seems it might be a while before they are running again.

So basically MIPgen should work better than ever now! Sorry for the past
inaccuracies.

Evan

On January 14, 2018 at 5:03:02 PM, Laurens Hannes (notifications@github.com)
wrote:

Hello,

I've been trying to reproduce results attained with version 0.9.1 using the
newest version of the MIPGEN tool. However only 1/4th of the results are
exactly the same. There remainder are different due to a difference in
logstical scoring. The same thing happens with the practice files provided.
I've tested using several different builds of hg19 and SNPdb builds. This
only provides minor differences and doesn't seem to account for the overal
difference.

Am I forgetting/doing something wrong or is this expected due to the
changes between the current version and older ones?

Thanks,
Laurens

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/30>, or mute the thread

**Comment by katib-UW** [comment]
Hi Evan,

If I'm reading the thread correctly, mip scoring is inaccurate for MIPgen v0.9.1 and fixed for v1.1?  We are currently running v1.0.  What is the status of the scoring in this version?

Thanks,

Kati
(Bamshad Lab, UW)

**Comment by augustboyle** [comment]
The MIP scoring was fixed prior to release of v1.0 on the GitHub so any use of code released on GitHub should not have been affected.
