### ISSUE TITLE
Is it possible to run Mipgen on a different organism (fasta)?

### ISSUE THREAD

**Issue by Flope** [shendurelab/MIPGEN#31]
Hi, 
I tried to run mipgen on a mouse but I noticed that I am getting the same svr score for every MIP (-3.81195) and the arm copies are suspiciously always 0. 
I also tried with Saccharomyces and I am getting again the same scores (-3.81195) and arm copies (0).

It works fine for the human genome.
Is that expected?

If I am using...
-score_method mixed: I am getting the constant score.
- logistic scores: I am getting "nan"
- svr score: the program seems to run forever.

thanks, 
Francesc

**Comment by augustboyle** [comment]
Hmm, that sounds bad.

Are you sure the chromosome names in the bed file are matching the genome
reference? Are you sure the whitespace is well behaved? Are the coordinates
actually included in the reference you are using, not off the end of the
chromosome?

My problem is usually one of those things (in one case the fasta was
truncated in a file transfer).

Evan Boyle
Stanford University


On March 29, 2018 at 2:32:40 PM, Flope (notifications@github.com) wrote:

Hi,
I tried to run mipgen on a mouse but I noticed that I am getting the same
svr score for every MIP (-3.81195) and the arm copies are suspiciously
always 0.
I also tried with Saccharomyces and I am getting again the same scores
(-3.81195) and arm copies (0).

It works fine for the human genome.
Is that expected?

If I am using...
-score_method mixed: I am getting the constant score.

   - logistic scores: I am getting "nan"
   - svr score: the program seems to run forever.

thanks,
Francesc

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/31>, or mute the thread

**Comment by augustboyle** [comment]
Hmm, well I have definitely used custom references and I think I have
tested in yeast. Other groups have used Arabidopsis and other species. I
don’t think you want to use the MIPs with invalid scores.

Could you send me your BED file of regions and the genome build you are
using? You can send me the progress file and standard error from the
program as well.

You will probably have to send it to my email address directly (eaboyle at
the domain stanford.edu <eaboyle@stanford.edu>) since Github will reject
attachments I think.

Evan

On April 4, 2018 at 6:18:49 AM, Flope (notifications@github.com) wrote:

thanks Evan for replying.
Yes. I checked all that.
I used different regions for both mouse and Saccharomyces.
The MIPs are designed and it seems they may work.
However, the scores and arm copies seem to be wrong.

I am not going to be able to do proper testing in the following days but I
could try single chromosomes for human and mouse and try to pinpoint the
issue.

Have you tried other genomes or fasta files?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/31#issuecomment-378596565>,
or mute the thread

**Comment by Flope** [comment]
Thanks Evan. 
In case somebody reads this:
As Evan found, It was a problem with the BWA index as clearly the error logs indicated and I missed:
[bwa_aln] fail to locate the index
[bwa_sai2sam_se] fail to locate the index

The sequence was collected using samtools faidx, but bwa were not able to map the sequence to the reference.
