### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tobsecret** [shendurelab/MIPGEN#32]
Could you add the documentation one gets when running ./mipgen doc to your official github webpage README? 
Would make it much easier for potential users to decide whether or not to use your software.

**Comment by augustboyle** [comment]
You got it!

Evan


On April 17, 2018 at 3:16:58 PM, tobsecret (notifications@github.com) wrote:

Could you add the documentation one gets when running ./mipgen doc to your
official github webpage README?
Would make it much easier for potential users to decide whether or not to
use your software.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/32>, or mute the thread
