### ISSUE TITLE
Failure Flag 1

### ISSUE THREAD

**Issue by ghost** [shendurelab/MIPGEN#34]
Hi, 
some of the MIPs that I designed show a failure flag. According to the readme it should consist of 3 bits. I just get "1". Does this then mean non-uniqueness, SNP problem or tandem repeat?
All the best
KP

**Comment by augustboyle** [comment]
Hello,

I think that could be a sign that the code is not running properly on your
targets. Does this happen when you run the example bed file? Also, are you
viewing this in a text editor? Sometimes I would save/open something as an
Excel file and the leading zeros would be lost. In general I suspect that
seeing a 1 suggests ‘001.’

Evan


On July 23, 2018 at 1:53:45 PM, Karlimero (notifications@github.com) wrote:

Hi,
some of the MIPs that I designed show a failure flag. According to the
readme it should consist of 3 bits. I just get "1". Does this then mean
non-uniqueness, SNP problem or tandem repeat?
All the best
KP

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/34>, or mute the thread
