### ISSUE TITLE
all_MIPs > collapsed_MIPs > picked_MIPs

### ISSUE THREAD

**Issue by ghost** [shendurelab/MIPGEN#35]
Hi,
sorry I have another question in this short amount of time. I was wondering what criteria are used to move an MIP from all > collapsed and from collapsed > picked. I was just wondering if I could pick MIPs myself from the collapsed_MIP or all_MIP file or if additional optimizations are taking place under the hood e.g. interaction minimization, so that it would be recommended to use the MIPs from the "picked" file. Thanks a lot
KP

**Comment by augustboyle** [comment]
No problem,

The parameters on the command line explain all the ways you can change the
prioritization of the MIP picking. If you want to avoid MIP arms with high
copy number you can set limits on the number of matches of each targeting
arm to your reference genome, or the metric of ligation x extension arm.
There is no support for testing the possibility of interactions currently.
You could set the max copy number to 1 but that would make it nearly
impossible to pick high scoring probes.

If there is something particular you want to screen the probes for, I would
start sifting through the collapsed MIPs. In general you just want to make
sure that the MIPs score decently well.

Evan

On July 24, 2018 at 1:30:34 PM, Karlimero (notifications@github.com) wrote:

Hi,
sorry I have another question in this short amount of time. I was wondering
what criteria are used to move an MIP from all > collapsed and from
collapsed > picked. I was just wondering if I could pick MIPs myself from
the collapsed_MIP or all_MIP file or if additional optimizations are taking
place under the hood e.g. interaction minimization, so that it would be
recommended to use the MIPs from the "picked" file. Thanks a lot
KP

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/35>, or mute the thread

**Comment by tdreal** [comment]
Hi, 
I have a similar question about how all_mips is filtered to the collapsed_mips file and the picked_mips. I was wondering what specific parameters there are in the program code (not what I could alter myself on the command line) that filters the mips into each file because when I examined them, because I can see there is such a huge difference in the amounts I'm getting in each. 

Thanks, 
Taylor

**Comment by augustboyle** [comment]
Are you asking for details on what the algorithm is doing? There is an
extended breakdown in the supplement, available from PubMedCentral.

Parameter-wise there might be one or two parameters that cannot be changed
from the options. It has something to do with the offset of where to start
looking for potential probes. For the most part it is very flexible,
however.

Best,
Evan

On January 30, 2019 at 1:55:02 PM, tdreal (notifications@github.com) wrote:

Hi,
I have a similar question about how all_mips is filtered to the
collapsed_mips file and the picked_mips. I was wondering what specific
parameters there are in the program code (not what I could alter myself on
the command line) that filters the mips into each file because when I
examined them, because I can see there is such a huge difference in the
amounts I'm getting in each.

Thanks,
Taylor

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/35#issuecomment-459124982>,
or mute the thread
