### ISSUE TITLE
-trf TRF directory invalid

### ISSUE THREAD

**Issue by MeganQiu** [shendurelab/MIPGEN#37]
I downloaded TRF 4.09 from https://tandem.bu.edu/trf/trf.download.html. But I feel confused about what -trf represents.  At  first, I use a directory, it returned TRF directory is not valid and threw circumstance 3.
if(args["-trf"] != "off")
	{
		a = system(args["-trf"].c_str());
		if (a != 65280)
		{
			cerr << "TRF directory invalid" << endl;
			throw 3;
		}
	}

In this part, what is the meaning of 'a != 65280'?

Thanks in advance for your reply.

**Comment by augustboyle** [comment]
Hi Megan,

The trf option is for providing the path to the executable — if you install
it system-wide then you can just use “trf.”

65280 is what is returned when trf successfully terminates. If it returns a
different value that means you do not have a trf executable that can be
executed properly.

Evan


On August 13, 2018 at 8:46:23 AM, Megan (notifications@github.com) wrote:

I downloaded TRF 4.09 from https://tandem.bu.edu/trf/trf.download.html. But
I feel confused about what -trf represents. At first, I use a directory, it
returned TRF directory is not valid and threw circumstance 3.
if(args["-trf"] != "off")
{
a = system(args["-trf"].c_str());
if (a != 65280)
{
cerr << "TRF directory invalid" << endl;
throw 3;
}
}

In this part, what is the meaning of 'a != 65280'?

Thanks in advance for your reply.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/37>, or mute the thread

**Comment by MeganQiu** [comment]
Thanks Evan for replying.
I checked my trf and ran it again.
The trf is under /usr/local/bin and when I type trf at the command line, it does run successfully. But if i used trf or /usr/local/bin/trf for the argument -trf in MIPgen, it returned 256 and threw circumstance 3 again saying TRF directory invalid. The most confusing thing is the description of trf is printed.

Those are the output:
Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.17-r1188
Contact: Heng Li <lh3@sanger.ac.uk>

Usage:   bwa <command> [options]

Command: index         index sequences in the FASTA format
         mem           BWA-MEM algorithm
         fastmap       identify super-maximal exact matches
         pemerge       merge overlapping paired ends (EXPERIMENTAL)
         aln           gapped/ungapped alignment
         samse         generate alignment (single ended)
         sampe         generate alignment (paired ended)
         bwasw         BWA-SW for long queries

         shm           manage indices in shared memory
         fa2pac        convert FASTA to PAC format
         pac2bwt       generate BWT from PAC
         pac2bwtgen    alternative algorithm for generating BWT
         bwtupdate     update .bwt to the new format
         bwt2sa        generate SA from BWT and Occ

Note: To use BWA, you need to first index the genome with `bwa index'.
      There are three alignment algorithms in BWA: `mem', `bwasw', and
      `aln/samse/sampe'. If you are not sure which to use, try `bwa mem'
      first. Please `man ./bwa.1' for the manual.



Please use: trf File Match Mismatch Delta PM PI Minscore MaxPeriod [options]

Where: (all weights, penalties, and scores are positive)
  File = sequences input file
  Match  = matching weight
  Mismatch  = mismatching penalty
  Delta = indel penalty
  PM = match probability (whole number)
  PI = indel probability (whole number)
  Minscore = minimum alignment score to report
  MaxPeriod = maximum period size to report
  [options] = one or more of the following:
        -m        masked sequence file
        -f        flanking sequence
        -d        data file
        -h        suppress html output
        -r        no redundancy elimination
        -l <n>    maximum TR length expected (in millions) (eg, -l 3 or -l=3 for 3 million)
                  Human genome HG38 would need -l 6
        -ngs      more compact .dat output on multisequence files, returns 0 on success.
                  Output is printed to the screen, not a file. You may pipe input in with
                  this option using - for file name. Short 50 flanks are appended to .dat
                  output.

See more information on the TRF Unix Help web page: https://tandem.bu.edu/trf/trf.unix.help.html

Note the sequence file should be in FASTA format:

>Name of sequence
aggaaacctgccatggcctcctggtgagctgtcctcatccactgctcgctgcctctccag
atactctgacccatggatcccctgggtgcagccaagccacaatggccatggcgccgctgt
actcccacccgccccaccctcctgatcctgctatggacatggcctttccacatccctgtg
256
TRF directory invalid
unable to tile sequences due to circumstance 3

**Comment by augustboyle** [comment]
Hm, it seems like maybe the new release of Tandem Repeats Finder might
return a different value from what is expected. Can you try downloading
4.07b and using that? If that works then the that settles things. I could
always just remove the check from the source code to get it working.

Evan


On August 14, 2018 at 12:55:15 AM, Megan (notifications@github.com) wrote:

Thanks Evan for replying.
I checked my trf and ran it again.
The trf is under /usr/local/bin and when I type trf at the command line, it
does run successfully. But if i used trf or /usr/local/bin/trf for the
argument -trf in MIPgen, it returned 256 and threw circumstance 3 again
saying TRF directory invalid. The most confusing thing is the description
of trf is printed.

Those are the output:
Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.17-r1188
Contact: Heng Li lh3@sanger.ac.uk

Usage: bwa [options]

Command: index index sequences in the FASTA format
mem BWA-MEM algorithm
fastmap identify super-maximal exact matches
pemerge merge overlapping paired ends (EXPERIMENTAL)
aln gapped/ungapped alignment
samse generate alignment (single ended)
sampe generate alignment (paired ended)
bwasw BWA-SW for long queries

     shm           manage indices in shared memory
     fa2pac        convert FASTA to PAC format
     pac2bwt       generate BWT from PAC
     pac2bwtgen    alternative algorithm for generating BWT
     bwtupdate     update .bwt to the new format
     bwt2sa        generate SA from BWT and Occ

Note: To use BWA, you need to first index the genome with bwa index'. There
are three alignment algorithms in BWA:mem', bwasw', andaln/samse/sampe'. If
you are not sure which to use, try bwa mem' first. Pleaseman ./bwa.1' for
the manual.

Please use: trf File Match Mismatch Delta PM PI Minscore MaxPeriod [options]

Where: (all weights, penalties, and scores are positive)
File = sequences input file
Match = matching weight
Mismatch = mismatching penalty
Delta = indel penalty
PM = match probability (whole number)
PI = indel probability (whole number)
Minscore = minimum alignment score to report
MaxPeriod = maximum period size to report
[options] = one or more of the following:
-m masked sequence file
-f flanking sequence
-d data file
-h suppress html output
-r no redundancy elimination
-l maximum TR length expected (in millions) (eg, -l 3 or -l=3 for 3 million)
Human genome HG38 would need -l 6
-ngs more compact .dat output on multisequence files, returns 0 on success.
Output is printed to the screen, not a file. You may pipe input in with
this option using - for file name. Short 50 flanks are appended to .dat
output.

See more information on the TRF Unix Help web page:
https://tandem.bu.edu/trf/trf.unix.help.html

Note the sequence file should be in FASTA format:

Name of sequence
aggaaacctgccatggcctcctggtgagctgtcctcatccactgctcgctgcctctccag
atactctgacccatggatcccctgggtgcagccaagccacaatggccatggcgccgctgt
actcccacccgccccaccctcctgatcctgctatggacatggcctttccacatccctgtg
256
TRF directory invalid
unable to tile sequences due to circumstance 3

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/shendurelab/MIPGEN/issues/37#issuecomment-412786610>,
or mute the thread

**Comment by MeganQiu** [comment]
Thanks Evan! It works now. You are right. It is the matter of the TRF version.
