### ISSUE TITLE
Alignment of MIPs among each other 

### ISSUE THREAD

**Issue by juliac224** [shendurelab/MIPGEN#44]
Hello, 

I have a question concerning MIP design. 
Are all the MIPs also aligned among each other to reduce possibility of primers binding to one another? Or is it possible to design MIPs for different genes separately and still use them in one assay? 

Thank you in advance, 

Julia

**Comment by augustboyle** [comment]
Hi Julia,

MIP interactions are not considered during tiling.

There are some relevant parameters that change binding within targeted regions: seal_both_strands and half_seal_both_strands come to mind.

Otherwise, the MIP arm copy number limits would tune the number of exact matches permitted for each arm separately.

In short, designing MIPs for genes separately and then combining them is more or less the same assuming you run with the same options, including default options. It is advisable to test a new candidate pool of MIPs first since it is possible that two pools could work separately but not together. I have not encountered this, so it remains something of a theoretical problem as far as I know.

Best,

Evan
On Apr 25, 2021, 11:33 PM -0700, juliac224 ***@***.***>, wrote:

Hello,

I have a question concerning MIP design.
Are all the MIPs also aligned among each other to reduce possibility of primers binding to one another? Or is it possible to design MIPs for different genes separately and still use them in one assay?

Thank you in advance,

Julia
