### ISSUE TITLE
Can the MIP backbone sequence be replaced? 

### ISSUE THREAD

**Issue by zpc975571872** [shendurelab/MIPGEN#46]
Hi, great creator. Sincerely ask you for advice.
1. Can the MIP backbone sequence be replaced to adapt to the MGI sequencing strategy? I plan to insert the primers required for sequencing and the primers for rolling circle amplification directly into the probe backbone, so that rolling circle amplification and sequencing can be performed directly after capture. Failed to capture after try. (Need to add 43nt to the backbone sequence)
2. I have 33 probes. Is it because the number of no probes is too small and the capture effect is not good? The molar ratio of 800:1 is using aged FFPE samples.
Do you have any good suggestions? Looking forward to your enlightenment ！

**Comment by augustboyle** [comment]
Hello,

1. Yes, you may certainly use different MIP backbones. I cannot comment on the change in performance since I have not done so, but it should be feasible.
2. Capture of FFPE samples can be very difficult. You should examine the size distribution on a gel/bioanalyzer and confirm that the MIP capture size is well under the fragment size. In general, we had poor luck with using fewer than 48 probes. I am not sure why this was the case, but you can try higher ratios of probe to template when the number of probes is small.

Best,

Evan

**Comment by zpc975571872** [comment]
Thanks for your prompt help ，Evan!

      I will try to synthesize more probes. Regarding question 1, you think the backbone sequence is lengthened to 90nt (including 8bp tags), and the arm length is 40nt, for a total of 130nt. How does this affect capture efficiency? Do I need to make adjustments? Is there an appropriate range for both the backbone sequence and the capture range?

Best,

Peng Cheng Zhang

**Comment by zpc975571872** [comment]
Thanks for your prompt help ，Evan!

I will try to synthesize more probes. Regarding question 1, you think the backbone sequence is lengthened to 90nt (including 8bp tags), and the arm length is 40nt, for a total of 130nt. How does this affect capture efficiency? Do I need to make adjustments? Is there an appropriate range for both the backbone sequence and the capture range?

Best,

Peng Cheng Zhang

**Comment by augustboyle** [comment]
I can't say with much certainty how changes in the backbone will affect capture, but from the testing I did years ago, it did not seem to matter a whole lot, at least with the enzymes used at the time.
