### ISSUE TITLE
Picked_mips depend on the set of positions

### ISSUE THREAD

**Issue by Skorn33** [shendurelab/MIPGEN#47]
Hi! 
I have a set of 1400 positions that I've selected because mipgen already found a picked_mip on them, but when I went to build my final file only 1300 positions came out with a picked mip, then I relaunched migen with the 100 positions and 93 positions had a picked mip. 

It is like the positions with a picked mips depend on the set of positions, is that possible or am I doing something wrong ?

**Comment by Skorn33** [comment]
Can I just merge the several picked_mips files ?

**Comment by augustboyle** [comment]
Hello,

While I’m not sure what options you provided the software, I can say that if there are leftover positions, there should be a BED file labeled as such, and this is much more likely when attempting to double tile or more. You can run the leftover positions to tile them again, but this will mean that some of the MIPs will ‘break the rules’ of MIPs not binding to the same strand of nucleotides.

To be honest, it’s not clear if that’s really a bad thing, but it stands to reason that it could increase the likelihood of false positives since the MIPs will be binding many of the identical nucleotides and could have the same off targets.

Also note that very low scoring MIPs could also be a factor, and those seldom work, so even if you pooled more of them it’s probably not a good idea if that applies.

Evan

**Comment by Skorn33** [comment]
Thank you so much for your fast answer. From what you say I guess that cutting up the file of positions and merging several picked_mip file is not a great idea and could induce errors?

**Comment by augustboyle** [comment]
Yes, I would generally advise against it.

If you are targeting a long region or a small number of genes, it could be worth trying. If there are particular positions you want to capture, I would shrink the regions as much as possible so that the tiling is easier there.

Evan
