### ISSUE TITLE
VCF file not being loaded

### ISSUE THREAD

**Issue by simonzeilmann** [shendurelab/MIPGEN#48]
Hello,

I'm using mipgen with [hg38](https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/latest/hg38.fa.gz) indexed with bwa and the corresponding [refGene](https://hgdownload.cse.ucsc.edu/goldenpath/hg38/database/refGene.txt.gz). 

This works well with an [older](https://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/00-All.vcf.gz) vcf file (apart from a warning about date mismatch) but when I try to use the [latest](https://ftp.ncbi.nih.gov/snp/latest_release/VCF/GCF_000001405.40.gz) version it never loads any snps and the snps_mips file is empty apart from the headers. But no error is displayed.

Is there a special conversion or other flag needed to use newer vcf files?

**Comment by augustboyle** [comment]
I wonder if it is related to the file not ending in .vcf.gz. In any case, I advise against using the all SNPs in dbSNP - these include less common variation and population specific variation that is unlikely to occur in DNA samples. The older file contains only SNPs above 1% frequency (and I don't expect the list of such SNPs to change very much over time).

If you are making your own VCF for a specific population then I would be interested in learning more if the indexed VCF file still did not work as expected.

**Comment by merondun** [comment]
After a few hours of troubleshooting I found that this can be caused due to a "chr" or "chr_" prefix in the genome `.fa`. I couldn't get any SNPs to load on my cuckoo genome - otherwise the whole run would proceed correctly but it would display:

> [mipgen] all 0 snps loaded; generating files for bwa
 
After downloading / indexing, etc the files mentioned above for hg38 for sanity checks I got it to load in the files and noticed the `.fa` sequences have 'chr' prefixies but the `.vcf.gz` do not, but it seems to work fine. Perhaps in my case it has something to with the "chr_" string and either the fasta / vcf / bed indexer not stripping underscores. 

Another random note in case anyone first runs on a smaller subset of dummy data, it also seems to only load SNPs within the probe vicinity, so in my case it will still only say 'all 334 snps loaded' on a huge VCF. I'm sure this is working as intended, but you'll need to make sure your `.fa`, regions file, and VCF all have concordant labels and that SNPs actually occur in the vicinity of the probes. Try stripping the prefix if it still doesn't work. 

VCFS can of course be renamed with: 

```
bcftools annotate  --rename-chrs chr_rename.txt $old_vcf -Oz -o stripped_vcf.gz

head chr_rename.txt #tab sep
chr_1   1
chr_2   2
```

Working great ✌️
