### ISSUE TITLE
Relaxing the "capture_size" parameters results in a worse design

### ISSUE THREAD

**Issue by francois-lecoquierre** [shendurelab/MIPGEN#50]
Hello,
I am in the process of designing a smmip panel on secific variants (snvs/indels). As I am trying to capture point mutations, the size of the captured region is not very important and does not need to be fixed. By allowing parameters between 70 and 95 (-min_capture_size = 70, -max_capture_size = 95), I am noticing that my design has worse metrics than when I use a fixed value of 94 (-min_capture_size = 94, -max_capture_size = 94), as evaluated by the number of gaps and the average logistic score on my regions of interest. Is this the expected normal behavior? Intuitively I was anticipating that relaxing these parameters would give more freedom to MIPGEN to make a better design. Did I miss some important info ?
Thanks for your insights!
François

**Comment by augustboyle** [comment]
I believe it will depend on the regions being tiled. Note that with shorter capture sizes a greater proportion of the target will be tiled with oligo arms. If you are double tiling this is even more pronounced: a promising hybridization site can only be used once, so it may place one slightly better MIP and one low scoring MIP instead of one larger middling MIP.

**Comment by francois-lecoquierre** [comment]
Thank you @augustboyle 
I am only aiming for one smmip per variant, with a tiling of just 1 (variants are in distinct genes). Also my targets are very small and consist in the variant position (usually 1 nucleotide). Is there some other parameters that I could use ? 
Thanks again

**Comment by augustboyle** [comment]
What kinds of scores are you getting? If they are already above 0.98 for logistic scoring then they will be accepted regardless. You can change this with the -logistic_optimal_score flag but it shouldn’t matter (similar for SVM scoring).  Otherwise if there are no variants nearby each other and you are providing individual nucleotides to capture I agree that outcome is surprising. I am happy to investigate if you send me a BED file of some of your regions of interest.

**Comment by francois-lecoquierre** [comment]
I obtain mean logistic scores at about 0.9 on my positions of interest.
Here is the list of my regions of interest and the parameters I used for the tests.
With the fixed capture size (94nt), I obtain 31 gaps, while using the 70-110 nt range ("variable capture size"), i obtain 51 gaps.
Thank you !

---

regions_to_scan=positions.txt
bwa_genome_index=/media/adm-loc/DATA_1To1/genome/grch38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
snp_file=/media/adm-loc/DATA_1To1/genome/snps_communs/grch38/common_all_20180418.vcf.gz

project_name=fixed_capture_size
MIPGEN/mipgen -project_name $project_name -bwa_genome_index $bwa_genome_index -regions_to_scan $regions_to_scan -min_capture_size 94 -max_capture_size 94 -arm_length_sums 40 -snp_file $snp_file -tag_sizes 8,0

project_name=variable_capture_size
MIPGEN/mipgen -project_name $project_name -bwa_genome_index $bwa_genome_index -regions_to_scan $regions_to_scan -min_capture_size 70 -max_capture_size 110 -arm_length_sums 40 -snp_file $snp_file -tag_sizes 8,0



[positions.txt](https://github.com/shendurelab/MIPGEN/files/11385294/positions.txt)

**Comment by augustboyle** [comment]
Hello, thanks for your patience.

I was able to identify the issue. MIPgen has different behavior when attempting to finish a region of interest. I added this to limit the amount of extraneous sequence captured by a MIP beyond the region of interest, but I see it results in the shortest capture size always being selected to finish the region. In your case, the regions are single nucleotides so this happens with every MIP. 

This is not desirable behavior. I might revise it at some point, perhaps to account specifically for single nucleotide regions. BUT I think the flexibility in capture size is not so important in single nucleotide capture. Indeed, having uniform capture_size probably outweighs having more choice in capture_size when there is no tiling. My recommendation is to run separate designs with fixed capture sizes and pick the design with the highest scores. Because MIPgen was evaluated on sequences with capture sizes larger than 90 or so, I would further advise staying above that for scores to be trustworthy.

**Comment by francois-lecoquierre** [comment]
Thank you @augustboyle for troubleshooting this, and thank you for the workaround
Best
François

**Comment by francois-lecoquierre** [comment]
Yay I managed to improve my design (hopefully). Y value is logistic score, set to 0 if no design.
Thanks again
François

![designs_mipgen](https://github.com/shendurelab/MIPGEN/assets/62658118/4119102d-31b8-4c70-8fcd-a9762f0da6e3)
