### ISSUE TITLE
 Can MIP be applied to RNA-Seq? Has anyone done it, I can't catch cDNA。

### ISSUE THREAD

**Issue by zpc975571872** [shendurelab/MIPGEN#51]
Dear Even or augustboyle or his associate!
   I tried to do RNA-seq, to capture cDNA after RNA reverse transcription, which should be theoretically possible, right? But I performed enzyme 1 digestion after a capture protocol at 95 °C for 8 min, 24 h, but there were no results. Dear sister brother, who has good advice or ideas.
       Looking forward to your response！

**Comment by augustboyle** [comment]
Hello, I have not performed cDNA capture. I agree that it should be possible if MIPs are designed against the transcriptome. Common reasons for failure are targeting regions of extreme GC content or using a small number of MIP oligos. It's unclear why, but MIPs that performed well in a large pool were hard to amplify specifically when I had a small number of them (say <30). There may be some protocol optimization to work on cDNA - if it is total RNA/cDNA perhaps you need more input because of all the rRNA. If it is polyA selected maybe coverage is lower at the 5' end of transcripts.

**Comment by zpc975571872** [comment]
> Handsome augustboyle.
You have a point, because it's cDNA of total RNA, so I may need to increase the input. My MIP is designed for DNA duplexes, so I guess it should work in cDNA.Thank you, I'll try to increase the amount of cDNA tomorrow.
Thanks again for sharing
