### ISSUE TITLE
Segmentation fault error when using SVR or MIXED scoring

### ISSUE THREAD

**Issue by Flope** [shendurelab/MIPGEN#9]
Hi, 
I am gertting a Segmentation fault error when running MIPGEN with SVR or MIXED scoring. 
Here are the last lines of the log:

```
...
[mipgen] checking oligo copy
[mipgen] bwa copy number analysis finished
[mipgen] file of all mips ready for write: ABL1_soft2.all_mips.txt
[mipgen] file of collapsed mips ready for write: ABL1_soft2.collapsed_mips.txt
[mipgen] feature #1
Segmentation fault
```

Do you have suggestions on how to solve this issue?

The compilation didn't give errors. 
OS: Red Hat Enterprise Linux Server release 6.2

thanks, 
F

**Comment by augustboyle** [comment]
Hello,

Segmentation faults are unfortunately common with MIPgen while being difficult to troubleshoot.

It usually has to do with improper input (I try to make the parsing robust, but it's surprisingly difficult to account for everything in C++, even using Boost functions) or incompatible environment settings.

Culprits in the past have been 1) weird whitespace patterns that trip up parsing, 2) chromosome names inconsistently matching the provided BED file, 3) language settings of the Linux environment/BWA package being set to a language that uses commas instead of decimals, 4) running out of memory, 5) chromosomes being shorter than the coordinates being provided and 5) strange non-ATCG(N) sequences in the reference. 

Also note that the SVR or mixed scoring relies on larger sequence contexts and will not work if the chromosomes/accessions you're designing to lack sufficient flanking sequence.

To home in on the problem 1) Confirm that you can run the example command that comes with the package. Instructions are on the website, 2) Run a few lines of your BED file before running the whole thing, and 3) Isolate at which input the program fails.

This will tell you whether 1) your environment is not set up properly and cannot use BWA as expected, 2) your input is not formatted properly OR your targets do not exist in some way as you are querying them, or 3) you have inadequate resources to run the whole job at once and can either break it up or use more memory OR only some of your targets are weird/do not exist.

I hope that helps!

Evan Boyle

**Comment by Flope** [comment]
I should have added that, when using "logistic" score method it works fine.

**Comment by Flope** [comment]
I found a solution. 
It works if I give the full path to the executable, mipgen. 
If I use the PATH variable to run it, it doesn't work for mixed and svr score methods.
It works for logistic method, though. 
Some sort of problem with filehandles in the code?

**Comment by augustboyle** [comment]
Thanks for the solution!
